# Generated by Django 4.1.6 on 2023-02-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smokerecord',
            old_name='value',
            new_name='hydrogen',
        ),
        migrations.RemoveField(
            model_name='smokerecord',
            name='gas_type',
        ),
        migrations.RemoveField(
            model_name='smokerecord',
            name='raspberry',
        ),
        migrations.RemoveField(
            model_name='thiefrecord',
            name='raspberry',
        ),
        migrations.AddField(
            model_name='smokerecord',
            name='lpg',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smokerecord',
            name='methan',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smokerecord',
            name='smoke',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
