# Generated by Django 2.2.28 on 2023-02-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_system', '0002_rename_value_smokerecord_hydrogen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspberry',
            name='admin_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='raspberry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='raspberry',
            name='user_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='smokerecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='thiefrecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
