# Generated by Django 2.2.28 on 2023-02-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_system', '0004_auto_20230207_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
